function [scenario, egoVehicle, egoWaypoints, actorWaypoints, allStatus, roadConfigs] = ds4_bend_Scenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 27-Aug-2023 22:11:23

% Construct a drivingScenario object.
scenario = drivingScenario("SampleTime",1.0,"StopTime",30.0);
actorWaypoints = cell(0);
allStatus = cell(0);
roadConfigs = cell(0);
egoWaypoints = [-143.1 6.8 deg2rad(20.3566);
    -137.4 8.9 deg2rad(19.9613);
    -135.29 9.66 deg2rad(19.6488);
    -76.8 20 deg2rad(-4.7982);
    -32.5 -8.7 deg2rad(-70.8816);
    -63.6 -58.5 deg2rad(-167.5034);
    -134.5 -34.2 deg2rad(145.5100)];


% Add all road segments
roadCenters = [-146.7 11.3 0;
    -71.2 24.5 0;
    -32 3.3 0;
    -46.8 -57.6 0;
    -145.3 -34 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.93 0.96 0])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-143.1 6.8 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-136.000157281943 12.8662977899777 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-136.000157281943 12.8662977899777 0;
    -79.4 23.2 0;
    -41.7 11.3 0;
    -29 -33 0;
    -84.1 -61.8 0;
    -142.3 -32.3 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [15;15;15;15;15;15];
waittime = [0;0;0;0;0;0];
yaw = [NaN;NaN;NaN;NaN;NaN;NaN];
car1Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car1Status;
trajectory(car1, waypoints, speed);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-130.4 10.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [-130.4 10.9 0;
    -87.8 20.1 0;
    -41.3 6.7 0;
    -33.1 -33.4 0;
    -93.6 -56.2 0;
    -140.5 -30.1 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;10];
waittime = [0;0;0;0;0;0];
yaw = [NaN;NaN;NaN;NaN;NaN;NaN];
car2Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car2Status;
trajectory(car2, waypoints, speed);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-144.1 10.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
waypoints = [-144.1 10.1 0;
    -126.1 14.8 0;
    -111 16.6 0;
    -63.7 17.9 0;
    -30.4 -24.5 0;
    -108 -50.6 0;
    -131 -36.7 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;10;10];
waittime = [0;0;0;0;0;0;0];
yaw = [NaN;NaN;NaN;NaN;NaN;NaN;NaN];
car3Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car3Status;
trajectory(car3, waypoints, speed);

