function [scenario, egoVehicle, egoWaypoints, actorWaypoints, allStatus, roadConfigs] = ds6_emergency_break_and_crowded_scenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 27-Aug-2023 21:41:01

% Construct a drivingScenario object.
scenario = drivingScenario("SampleTime",1.0,"StopTime",30);
actorWaypoints = cell(0);
allStatus = cell(0);
egoWaypoints = [-85.6111046505973 14.5423662360762 0;
    -76.1 14.5424 0;
    -70.3 14.5424 0;
    133.8 14.5424 0];
roadConfigs = cell(0);

% Add all road segments
roadCenters = [-87.9 20.4 0;
    135.6 20.4 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.96 0.93 0])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(6, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-85.6111046505973 14.5423662360762 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-85.3 18.4 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-85.3 18.4 0;
    0.71 18.73 0;
    5.5 18.73 0;
    126.3 19 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;12;0;12];
waittime = [0;0;2;0];
yaw = [NaN;NaN;NaN;NaN];
car1Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car1Status;
trajectory(car1, waypoints, speed, waittime);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-82.8994363470262 11.411712825494 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [-82.8994363470262 11.411712825494 0;
    -2 11.6 0;
    2.3 11.7 0;
    126.29 11.68 0.01];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;12;0;12];
waittime = [0;0;2;0];
yaw = [NaN;NaN;NaN;NaN];
car2Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car2Status;
trajectory(car2, waypoints, speed, waittime);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-74.5932177632436 14.3939452003597 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
waypoints = [-74.5932177632436 14.3939452003597 0;
    12 14.4 0;
    16.98 14.4 0;
    134.1 14.4 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;12;0;12];
waittime = [0;0;2;0];
yaw = [NaN;NaN;NaN;NaN];
car3Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car3Status;
trajectory(car3, waypoints, speed, waittime);

car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-70.3998603567377 18.3068174545491 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');
waypoints = [-70.3998603567377 18.3068174545491 0;
    13.31 18.69 0;
    16.8 18.7 0;
    133.8 19.1 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;12;0;12];
waittime = [0;0;2;0];
yaw = [NaN;NaN;NaN;NaN];
car4Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car4Status;
trajectory(car4, waypoints, speed, waittime);

car5 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-74.5 11.4 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car5');
waypoints = [-74.5 11.4 0;
    12.53 11.74 0;
    16.63 11.77 0;
    132.9 11.3 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;12;0;12];
yaw =  [1;NaN;NaN;NaN];
waittime = [0;0;2;0];
car5Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car5Status;
trajectory(car5, waypoints, speed, waittime, 'Yaw', yaw);

