function [scenario, egoVehicle, egoWaypoints, actorWaypoints, allStatus, roadConfigs] = ShanghaiCenturalAvenue()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 24-Feb-2024 01:32:33

% Construct a drivingScenario object.
scenario = drivingScenario('GeographicReference', [31.229135 121.52591 0], ...
    'VerticalAxis', 'Y', "SampleTime", 1.0, "StopTime", 25.0);
actorWaypoints = cell(0);
allStatus = cell(0);
egoWaypoints = [33.9413892435276 -86.6802303860717 deg2rad(112.6804);
    23.6 -62.2 deg2rad(113.3425);
    14.8 -41.6 deg2rad(112.1512);
    7.2 -22.9 deg2rad(113.6270);
    4.2 -6.7 deg2rad(71.4468);
    24.1 4.5 deg2rad(9.6462);
    42.3 8.3 deg2rad(14.5752);
    86.3 24.6 deg2rad(23.2026)];
roadConfigs = cell(0);

% Add all road segments
roadCenters = [-188 103.3 -0.00047230673482623;
    23.5 -37.7 0;
    203.5 -160.7 -4.9076299183604e-05];
marking = [laneMarking([laneMarking('Solid') laneMarking('Solid')], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec([2 2], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '世纪大道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-368.4409367824 202.32827535188 -0.01385419927243;
    -15.1 -34.2 0;
    35 -69.5 0;
    210 -183 -0.00017159742373263];
marking = [laneMarking([laneMarking('Solid') laneMarking('Solid')], 'SegmentRange', [0.5 0.5])
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Solid')];
laneSpecification = lanespec([1 1], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '世纪大道辅路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [273.71336045458 99.479188931267 -0.0066467299504183;
    195.97012629705 70.217958295481 -0.0033959868097568;
    102.24892527909 36.433500212125 -0.00092332571568932;
    49.523938727123 16.686564996134 -0.00021401085786277;
    46.027351856266 15.50020360624 -0.00018483793903368;
    -222.7 -81.7 -0.00011271662805346];
marking = [laneMarking([laneMarking('Solid') laneMarking('Solid')], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec([2 2], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '潍坊路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [102.84187568641 -268.90450736222 -0.0077386835986601;
    38.309526966849 -113.11681327517 -0.0016579957617679;
    25.1 -79.9 -0.00086442541324061;
    16.3 -58.4 -0.00055767823619846;
    -2 -6.6 0;
    -51.4 105.8 -0.00021714160676467];
marking = [laneMarking([laneMarking('Solid') laneMarking('Solid')], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec([2 2], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '福山路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [212.31397067292 -141.39470617804 -0.0051041215420682;
    56.936632746594 -38.783364105358 -0.00037229220696133;
    38.596056566324 -26.676071403732 -0.00017268444698537;
    -76 46.2 -9.2281986607823e-07];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '世纪大道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-131.3 98.6 -7.0627523449218e-05;
    -4 14.8 0;
    117.7 -57.6 -9.8155009983003e-05];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '潍坊路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [35 12 -9.8155009983003e-05;
    -75.2 46.8 0;
    -155.4 105.2 -0.00062029904614747];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '潍坊路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [33.9413892435276 -86.6802303860717 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car', ...
    'Yaw', 112.6804);
% speed = [10;10;10;10;10;10;10;10];
% trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [28.3195652365962 -74.1914520895818 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [28.3195652365962 -74.1914520895818 0;
    16.4 -44.5 0;
    4 -12 0;
    -16.6 44.5 0;
    -34.6 83 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1, numel(speed));
car1Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car1Status;
trajectory(car1, waypoints, speed);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-61.5926519192269 12.6238007983659 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [-61.5926519192269 12.6238007983659 0;
    -33.3 -5.7 0;
    12 -36.7 0;
    41.6 -56.9 0;
    126.3 -114.3 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1, numel(speed));
car2Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car2Status;
trajectory(car2, waypoints, speed);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-76.8670386415885 27.7305760494993 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
waypoints = [-76.8670386415885 27.7305760494993 0;
    -55 12.7 0;
    -35 -0.3 0;
    -10.3 -6.8 0;
    9.6 -0.3 0;
    42.3 12 0;
    111 38 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1, numel(speed));
car3Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car3Status;
trajectory(car3, waypoints, speed);

car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-39.6237418405706 -20.0921914231867 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');
waypoints = [-39.6237418405706 -20.0921914231867 0;
    50.3 11 0;
    77.3 20.5 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1, numel(speed));
car4Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car4Status;
trajectory(car4, waypoints, speed, waittime);

car5 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [127.5 47.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car5');
waypoints = [127.5 47.9 0;
    114 43.9 0;
    84.1 31.8 0;
    7.8 3.4 0;
    -65.8 -20.9 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1, numel(speed));
car5Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car5Status;
trajectory(car5, waypoints, speed);

