function [scenario, egoVehicle, egoWaypoints, actorWaypoints, allStatus, roadConfigs] =  ShanghaiLujiazuiTunnel()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 22-Feb-2024 21:26:53

% Construct a drivingScenario object.
scenario = drivingScenario('GeographicReference', [31.236145 121.504815 0], ...
    'VerticalAxis', 'Y', "SampleTime", 1.0, "StopTime", 30.0);
actorWaypoints = cell(0);
allStatus = cell(0);
egoWaypoints = [-32.8679127794048 163.92406124332 deg2rad(-80.7323);
    -28.2 135.4 deg2rad(-80.6534);
    -24 109.3 deg2rad(-81.3404);
    -21.2 87.6 deg2rad(-84.6339);
    -20.5 72.8 deg2rad(-90.8034);
    -21.3 57.3 deg2rad(-92.6873);
    -21 29.4 deg2rad(-87.6070);
    -20.2 10 deg2rad(-87.8765);
    -18.6 -30.4 deg2rad(-86.5185);
    -20.7 -69.2 deg2rad(-108.4989);
    -24.43 -77.04 deg2rad(-123.9505);
    -47.4 -92.7 deg2rad(-156.5529)];
roadConfigs = cell(0);

% Add all road segments
roadCenters = [-20.539629041744 89.397354363754 -0.00066206903183286;
    -18.70097865812 84.651963194344 -0.00059141089910497;
    -16.557472319532 79.063932957949 -0.00051348402482887;
    -15.071306612413 75.172269337916 -0.00046256097432007;
    -12.965905674108 67.743739155516 -0.0003743763707611;
    -10.898610255548 58.896028185831 -0.00028232108104476;
    -9.2790713131013 47.797585266566 -0.00018656151141982;
    -7.4 23.1 -4.6724380798224e-05;
    -5.6208319915775 -25.811356241266 -5.4911370169108e-05;
    -4.1 -48.1 -0.00017551503993474;
    -2.8104243142311 -56.966818000639 -0.00025604342219054;
    -0.64782727210847 -67.533065014783 -0.00035899854582055;
    2.6961085830008 -82.789261058322 -0.00054004027407473;
    5.1064170129052 -96.005383499036 -0.00072749829310936];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-20.539629041744 89.427354363754 -0.00066206903183286;
    -20.863552902098 81.832517157084 -0.00056077997043502;
    -21.130305641322 79.781357118664 -0.00053557541290417;
    -21.644757560693 75.867522063166 -0.00048937098241453;
    -22.664135724624 68.073114133296 -0.00040463968473503;
    -23.17859359633 61.975070447046 -0.00034409587704687;
    -23.130988330488 49.00286610837 -0.00023067544120536;
    -20.025436505757 -42.434542375756 -0.00017333756089144;
    -20.654250872204 -64.010528841012 -0.00035620803891234;
    -24.42 -77.27 -0.0005180928008528];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [5.1064170129052 -96.005383499036 -0.00072749829310936;
    16.138602940194 -121.26235905971 -0.0011777668206676;
    22.39782249262 -136.74028983921 -0.0015109680559675];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '浦城路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-11.317892966182 -40.468826681749 -0.81680560145753;
    -9.2791577859722 -51.157037450304 -0.52287939260926;
    -6.4592166632965 -64.251203840983 -0.29432819153509;
    -3.4677833125645 -73.919377742348 -0.13109767579007;
    -0.33344101116665 -83.487764138185 -0.033215286808392;
    5.1064170129052 -96.005383499036 -0.00072749829310936];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路地道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-31.742739015363 193.5630253085 -1.995242380968;
    -23.749992911946 150.11167280991 -1.8866505062355;
    -19.767894735159 123.3357117545 -1.7673755248598;
    -16.185896605732 97.757186987902 -1.636931859997;
    -15.395194949914 87.002456525623 -1.4954816983416;
    -15.261862142688 58.696448831395 -1.342561618531;
    -15.319042640674 45.247492531259 -1.1785532260671;
    -14.2 4 -1.0031875192768;
    -11.317892966182 -40.468826681749 -0.81680560145753];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路地道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-206.42995085918 -156.04133734242 -1.230254027421;
    -189.0621430128 -146.49545118022 -1.4555906644604;
    -172.27556645013 -140.36443048164 -1.6878284044502;
    -56.313529870637 -106.51601117164 -1.9246950908372;
    -41.22289210994 -101.3715475875 -2.1708454968847;
    -31.686452040757 -97.09186047729 -2.4238233615432;
    -21.854682156406 -90.55034675733 -2.6835340053254;
    -14.128365029578 -83.110746538639 -2.9500083385054;
    -8.4408102755676 -75.338519287292 -3.2232484615225;
    -3.1914993551395 -64.583793265294 -3.5032216563693;
    -0.27627881643286 -56.20175753492 -3.7899869089887;
    1.3242315769041 -45.790737657 -4.0834985048031];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路地道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [1.3242315769041 -45.790737657 -4.0834985048031;
    -2.1 45.8 -4.2749007064371;
    -4.1441349872492 62.754378728627 -4.4409363070509;
    -6.2971672968662 83.47662869271 -4.5815411560036;
    -20.034531335483 176.7655821166 -4.6983240910309];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路地道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [22.39782249262 -136.74028983921 -0.0015109680559675;
    73.834423376765 -234.07590293 -0.0047395140937425];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '浦城路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-206.42995085918 -156.04133734242 -1.230254027421;
    -169.1032660861 -149.74439462319 -0.99625459769872;
    -42.556718671686 -114.09984235141 -0.78516653008894;
    -33.106014982719 -111.77153603935 -0.60131913259602;
    -23.331403550495 -111.07306195263 -0.44201367545899;
    -15.338326507097 -111.38352481544 -0.30724490233906;
    -7.3357232993259 -113.96688817096 -0.19702651197908;
    0.35249594129558 -118.20226041094 -0.11134970112786;
    7.3833640787649 -122.58176269863 -0.050186961872654;
    13.823570606987 -128.35826689889 -0.013561749613686;
    22.39782249262 -136.74028983921 -0.0015109680559675];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-11.317892966182 -40.468826681749 -0.81680560145753;
    -12.661192233807 -51.51182968585 -0.4595964044407;
    -14.976232106913 -60.758680244119 -0.20447479307542;
    -19.62 -69.82 -0.051447196869873;
    -22.67 -77.86 -0.0005180928008528];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路地道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-25.855469920576 119.62149528803 -0.0011786170605816;
    -22.044837319159 96.559788499285 -0.00077192177306529;
    -20.539629041744 89.397354363754 -0.00066206903183286];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-18 -49.6 -0.0005180928008528;
    -18.38 -60.88 0;
    -21.73 -73.54 0;
    -30.2 -83.3 0;
    -39.508017064312 -88.942667533506 -0.00074489605938055;
    -47.291503515484 -92.612548878124 -0.00085025367277325;
    -81.340704171791 -103.00118933835 -0.0013532382970922;
    -106.90146348222 -110.54035981658 -0.0018568082401202];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-106.90146348222 -110.54035981658 -0.0018568082401202;
    -209.32588020465 -140.77402809297 -0.0049916546785411];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-38.392327682737 197.04453801729 -0.0031714084832259;
    -36.267923740195 186.87742487714 -0.0028517582501024;
    -33.133722772229 166.53211641304 -0.0022687936150732;
    -32.304919771888 161.1880083749 -0.0021266981477339;
    -27.960835452319 133.04828775371 -0.0014545116328435;
    -26.350850887925 122.63725709439 -0.0012381467110885;
    -25.855469920576 119.62149528803 -0.0011786170605816];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-32.8679127794048 163.92406124332 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car', ...
    'Yaw', -80.7323);
% speed = [10;10;10;10;10;10;10;10;10;10;10;10];
% trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-30.1036280781539 148.935739078023 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-30.1036280781539 148.935739078023 0;
    -26.4 124.3 0;
    -23.8 107.1 0;
    -20.3 87.2 0;
    -14.6 66.1 0;
    -12.3 54.7 0;
    -9.2 22.6 0;
    -6.7 -38.6 0;
    -4.8 -60.6 0;
    0.5 -81.7 0;
    15.3 -120.1 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;10;10;10;10;10;10];
waittime = [0;0;0;0;0;0;0;0;0;0;0];
yaw = NaN(1, numel(speed));
car1Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car1Status;
trajectory(car1, waypoints, speed, waittime);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-28.2342145684363 135.685420352735 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [-28.2342145684363 135.685420352735 0;
    -25.4 117.4 0;
    -21.2 92 0;
    -20.9 65.1 0;
    -21.4 38.8 0;
    -20.4 13.8 0;
    -19.4 -13.9 0;
    -17.8 -48.5 0;
    -20.8 -70.4 0;
    -25.3 -78.1 0;
    -44.5 -91.9 0;
    -86.4 -104.3 0;
    -114.4 -112.9 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;10;10;10;10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1, numel(speed));
car2Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car2Status;
trajectory(car2, waypoints, speed);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-25.4270198697407 118.311447971206 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
waypoints = [-25.4270198697407 118.311447971206 0;
    -22.9 102.3 0;
    -21.5 91.5 0;
    -24.8 61.6 0;
    -24.2 36.7 0;
    -23.7 21.3 0;
    -21.8 -40.5 0;
    -21.75 -52.57 -0.02;
    -21.41 -59.56 -0.03;
    -24.59 -77.05 -0.01;
    -36.85 -87.66 0.01;
    -45.49 -91.99 0.01;
    -72.1 -100.4 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;7;4;7;10;10;10;10;10;10;10];
waittime = [0;0;0;0;0;0;0;0;0;0;0;0;0];
yaw = NaN(1, numel(speed));
car3Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car3Status;
trajectory(car3, waypoints, speed, waittime);

car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-16.0087275148158 58.6018951360394 -1.3], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');
waypoints = [-16.0087275148158 58.6018951360394 -1.3;
    -15.6 35.6 -1.1;
    -14.1 0 -1;
    -11.8 -36.3 -0.8;
    -12.6 -52.3 -0.4;
    -17.6 -65.1 -0.1;
    -26.1 -78.5 0;
    -58.4 -96.5 0;
    -99.5 -107.9 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [0;10;10;9;8;5;10;10;10];
waittime = [5;0;0;0;0;0;0;0;0];
yaw = NaN(1, numel(speed));
car4Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car4Status;
trajectory(car4, waypoints, speed, waittime);

