function [scenario, egoVehicle, egoWaypoints, actorWaypoints, allStatus, roadConfigs] = ShanghaiRoundabout()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 21-Feb-2024 23:30:46

% Construct a drivingScenario object.
scenario = drivingScenario('GeographicReference', [31.24012 121.496065 0], ...
    'VerticalAxis', 'Y', "SampleTime", 1.0, "StopTime", 25.0);
actorWaypoints = cell(0);
allStatus = cell(0);
egoWaypoints = [16.2536013228326 -38.5186708203269 deg2rad(81.5236);
    20.7 -18.2 deg2rad(69.9178);
    25.8 -7.9 deg2rad(57.5522);
    32.1 2 deg2rad(63.5530);
    35.6 15.4 deg2rad(84.6544);
    33.7 32 deg2rad(112.0827);
    23 44.8 deg2rad(146.2212);
    4.5 49.8 deg2rad(-174.9387);
    -8.1 46.3 deg2rad(-158.1375);
    -41.8 39.2 deg2rad(165.8623);
    -52 44.4000 deg2rad(137.5339);
    -78.5 71.8 deg2rad(129.1518)];
roadConfigs = cell(0);

% Add all road segments
roadCenters = [-27.7 0.7 -6.690688628963e-05;
    -35.028652892594 -11.231437344163 -0.00010603008631715;
    -44.621788302366 -17.994690531875 -0.00018143374280655];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴西路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [32.6 40.1 -0.00032959624847706;
    40.2 69.9 -0.00085443861541989;
    57 94.8 -0.001281930397802;
    71.370969247064 133.68055460745 -0.0018055113424964];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-15.6 43.9 -0.00013403795069777;
    -26.1 40.6 -0.00020377218282341;
    -49.9 44.7 -0.00033037736134744;
    -67.6 61.1 0;
    -110.3 85.4 -0.0018956994565187];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '丰和路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [2.2 -20.6 -1.6643454983978e-05;
    3.2 -26.2 0;
    4.4393200756539 -37.671056509107 -6.8061935808217e-05;
    5.8206576647874 -45.066324645657 -0.00010731808717068;
    6.7828351310034 -55.244519997034 -0.00017484877766094;
    5.8492532536199 -74.314778329694 -0.00034257576430008];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [59.310684398337 133.44679016193 -0.001685570567183;
    44.3 107.3 0;
    32.3 76.2 0;
    17.3 55.6 -0.001099156648678;
    12.8 51.7 -0.00034539666006239];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-49.861383058523 -30.534470796414 -0.00026810437350555;
    -30.06543012538 -26.276999878691 -0.00012514274532016;
    -19.567298251033 -26.243762553882 -8.4197302031797e-05;
    -11.9 -27.6 -7.4602487943665e-05;
    -2 -30.8 -8.6807796503052e-05;
    1.9 -34.8 -0.00011115782546511];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-77.449341722773 52.27718950851 -0.00068490892892115;
    -75.153533689413 45.868678315754 -0.00060796353198711;
    -56.091335320401 33.073745256566 -0.00033251494751241;
    -44.116718727023 22.296773864898 -0.00019156690640187;
    -39.382131973449 14.336030366044 -0.00013765021802925;
    -37.848406474711 7.4729487652158 -0.00011659034565259;
    -38.43905880167 3.3041034981733 -0.0001165842112707;
    -39.134505182577 -1.6852059657423 -0.0001201738645964;
    -41.687614120998 -9.3132998149043 -0.00014293924066777;
    -44.621788302366 -17.994690531875 -0.00018143374280655];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '167167541');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-76.049341722773 50.67718950851 -0.00068490892892115;
    -52.023930215233 35.066036208927 -0.00032935531568512;
    -43.850319882972 29.86602578172 -0.00023830129106628;
    -31.3 15 -0.00014536706201973];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '丰和路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [16.3 -49.8 -0.00016300833229721;
    21.5 -35.1 0;
    24.787796977444 -31.399373764765 -0.00012572260212451;
    30.103533139591 -25.323486840167 -0.00012145073158543;
    37.315026865887 -20.467200198677 -0.00014202788578643;
    45.48869405642 -18.183171936554 -0.00018808826661321;
    57.7 -18.3 -0.00025694506406815;
    84.5 -29.9 -0.00036565737547534];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '194474922');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [93.977961776493 9.9457816192903 -0.00069951504028598;
    79.6 13.6 -0.00068652648399059;
    40.1 21.9 -0.00048470685205437;
    37.8 23.9 -0.00020868278701869];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '世纪大道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [27.6 -9.9 -5.3438670522432e-05;
    49.3 -10.5 -0.00011194986136598;
    75.4 -18 -0.00023962311360126;
    92.8 -19.7 -0.00032905376621528];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '世纪大道');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [1.84812638614752 -14.4246551109483 -1.66434549839778e-05;
    19.3 -10.9 0;
    29.3 -1.1 0;
    32.1 5.8 0;
    31.6 31.1 0;
    18.2 44.9 0;
    -2.1 47 0;
    -19.8 35.1 0;
    -25.4 12.5 -4.12034098211667e-05;
    -17.1284958075272 -4.74537614549951 -2.47506173889356e-05;
    -9.2882608651967 -10.8101718643053 -1.59540835467098e-05;
    -3.88678079200396 -13.1385208149265 -1.47701262678268e-05;
    1.84812638614752 -14.4246551109483 -1.66434549839778e-05];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环岛');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [15.2 -60.8 -0.0002948129796394;
    14.423043161541 -40.845823352784 -0.00014760725233742;
    15.6 -29.9 -9.116715587254e-05;
    17.8 -21.7 -6.5215987822498e-05;
    18.8 -15.9 -5.3438670522432e-05];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Dashed')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


roadCenters = [-49.861383058523 -30.534470796414 -0.00026810437350555;
    -33.1 -18.4 0;
    -19.5 -15.4 0;
    -13.1 -15.2 -9.5795392642373e-05];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Solid')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴西路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;


% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [16.7357135376086 -57.5934948467249 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car', ...
    'Yaw', 81.2);

% speed = [10;10;10;10;10;10;10;10;10;10;10;10];
% trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [16.4353873620263 -48.2617954475674 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [75.8353873620263 11.9382045524326 0;
    54.1 14.3 0;
    40.1 22 0;
    34.9 35.8 0;
    17.5 48.4 0;
    4.5 49.6 0;
    -14.7 41.2 0;
    -49.5 42.4 0;
    -62.3 53 0;
    -82 69.6 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;3;7;10;8;5;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1,numel(speed));
car1Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car1Status;
trajectory(car1, waypoints, speed, waittime);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [17.7 -31.4 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [18.6462951412989 -27.5794983281722 0;
    23.8 -11.8 0;
    30.2 -2.3 0;
    35.4 9.4 0;
    36.4 32.3 0;
    34.2 37 0;
    36.2 57.7 0;
    42 72.9 0;
    51.8 87.2 0;
    62.2 104.3 0];
speed = [10;10;10;10;10;10;10;10;10;10];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
waittime = zeros(1, numel(speed));
yaw = NaN(1,numel(speed));
car2Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car2Status;
trajectory(car2, waypoints, speed);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [19.4614947934676 -14.870829443702 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
waypoints = [19.4614947934676 -14.870829443702 0;
    29.4 -4.9 0;
    34.5 6.3 0;
    36.7 23.5 0;
    33 34.1 0;
    22.2 44.4 0;
    6.1 46.4 0;
    -8.1 42.6 0;
    -21.4 29 0;
    -23.7 16.2 0;
    -17.2 -1.5 0;
    -2.5 -14.6 0;
    0.7 -24.1 0;
    3.8 -45.7 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;5;10;10;10;10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1,numel(speed));
car3Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car3Status;
trajectory(car3, waypoints, speed, waittime);

car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-2.71134189600047 -11.1204366869293 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');
waypoints = [-2.71134189600047 -11.1204366869293 0;
    15.1 -10.7 0;
    27.1 -0.9 0;
    32.1 12.8 0;
    31.1 29.2 0;
    22.9 41.1 0;
    12.4 45.5 0;
    -3.7 45.5 0;
    -25 43.3 0;
    -40.6 42.9 0;
    -58.4 54 0;
    -67.2 62.6 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;8;3;10;10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1,numel(speed));
car4Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car4Status;
trajectory(car4, waypoints, speed, waittime);

car5 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [70.7812510334284 15.9126456940748 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car5');
waypoints = [70.7812510334284 15.9126456940748 0;
    57.6 16.9 0;
    43.8 21 0;
    34.4 37.5 0;
    18.3 49.9 0;
    -0.2 47.4 0;
    -20.8 35 0;
    -24 9.2 0;
    -7.3 -10 0;
    5.7 -12.6 0;
    22.6 -7.3 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;10;10;10;10;10;10;10;10;10;10];
waittime = zeros(1, numel(speed));
yaw = NaN(1,numel(speed));
car5Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car5Status;
trajectory(car5, waypoints, speed);

