function [scenario, egoVehicle, egoWaypoints, actorWaypoints, allStatus, roadConfigs] = ShanghaiPudongSouthIntersection()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 22-Feb-2024 03:24:13

% Construct a drivingScenario object.
scenario = drivingScenario('GeographicReference', [31.23452 121.499725 0], ...
    'VerticalAxis', 'Y', "SampleTime", 1.0, "StopTime", 15.0);
actorWaypoints = cell(0);
allStatus = cell(0);
egoWaypoints = [17.1293569350258 -23.0936133851758 deg2rad(94.0946);
    15.2 -2.8 deg2rad(98.1036);
    13.6 3 deg2rad(118.8899);
    -4.8 8.6 deg2rad(-175.3966);
    -40.3 6 deg2rad(-176.0185)];
roadConfigs = cell(0);

% Add all road segments
roadCenters = [24.141545477474 -84.773848259433 -0.00061129077800359;
    21.473924076914 -61.57911943241 -0.00033457680035553;
    18.006009357327 -17.118853379044 -4.8458535138352e-05;
    15 11.5 -2.1523124891787e-05];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '银城中路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [1.6 6.5 -2.1405087513582e-07;
    2.1912079377553 -19.280901818776 -2.9636002247813e-05;
    10.613124820428 -75.626807560888 -0.00045898623844209];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '银城中路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [14.6 11.8 -2.9849678598204e-05;
    14.109416805014 23.183659473352 -5.7897000758089e-05;
    3.0200166544725 118.41291230785 -0.0011043303092748];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '银城中路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-61.59176103284202 21.05505886530017 -0.0003320118599727806;
    -46.00565731713348 22.45198539969894 -0.0002054466722896109;
    -43.55722707147122 23.23917688682693 -0.0001911021874647645;
    -41.26122581255152 24.69161058523067 -0.0001813296090720229;
    -39.21292369726848 26.73167529809513 -0.000176675376371449;
    -38.66034870130463 29.98026704511526 -0.0001878069332299503;
    -40.10843455055043 32.60797461760401 -0.00020968456027326;
    -42.92840321330259 34.27108837435194 -0.0002367799025257966;
    -45.32918820523471 35.32439677602802 -0.0002591443282842221;
    -47.920516071448 35.37984500845643 -0.0002783789988871632;
    -79.10221672528917 32.59710806119966 -0.0005737071039391139;
    -82.7891489676414 31.97624476269756 -0.0006173005812186716;
    -85.81873074232082 30.33534109712224 -0.0006492612081743232;
    -87.94325992175114 27.91831615168694 -0.0006670927560747941;
    -88.38152281573225 25.14648212369929 -0.0006615683385948756;
    -87.69560101552358 22.90683153502258 -0.000643638096484267;
    -85.3234068301349 20.80021540443514 -0.0006042452912762286;
    -82.09377841990072 19.6138431965265 -0.0005581237952316798;
    -78.16867286335389 19.58055126623549 -0.0005087516679438409;
    -61.59176103284201 21.05505886530018 -0.0003320118599727805];
marking = [laneMarking([laneMarking('Solid') laneMarking('Solid')], 'SegmentRange', [0.5 0.5])
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Solid')];
laneSpecification = lanespec([1 1], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '965004708');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-60.105641400665 6.1203890298385 -0.00028590147672336;
    -61.591761032842 21.0550588653 -0.00033201185997278];
marking = [laneMarking([laneMarking('Solid') laneMarking('Solid')], 'SegmentRange', [0.5 0.5])
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Solid')];
laneSpecification = lanespec([1 1], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '965004709');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [6.9 3.6 -2.1523124891787e-05;
    32.048735696775 1.1309585255605 -8.0547209133974e-05;
    164.38769820904 14.791809116144 -0.0021337466452183];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-114.22851481718 -9.3571038953495 -0.001028851113591;
    -87.705382650442 -7.6609937039688 -0.00060709315381491;
    -53.836953471474 -5.0335193856917 -0.00022900405224258;
    -7.8 0.6 -9.800406308047e-06;
    7.1 3.6 -2.1405087513582e-07];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [6.1 9.8 -9.0244559993735e-06;
    -11.956340779193 9.7457878394051 -1.8671893510458e-05;
    -37.059899804057 7.7944725933639 -0.00011235213817473;
    -60.105641400665 6.1203890298385 -0.00028590147672336];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [164.3875273162 25.735024249601 -0.0021686491623303;
    100.14736151523 19.425514510145 -0.00081523327179944;
    30.981678776228 13.3603029224 -8.9227412251702e-05;
    5.8 9.8 -2.9849678598204e-05];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-60.105641400665 6.1203890298385 -0.00028590147672336;
    -109.17908979107 2.6504429259579 -0.00093415867125413];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '陆家嘴环路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

roadCenters = [-6.8117434102865 65.991914709801 -0.00034640295666222;
    1.3 22 -3.4521294960399e-05;
    2.1 6.6 -9.0244559993735e-06];
marking = [laneMarking([laneMarking('Solid', 'Color', [0.98 0.86 0.36]) laneMarking('Solid', 'Color', [0.98 0.86 0.36])], 'SegmentRange', [0.5 0.5])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '银城中路');
tempRoad = struct('roadCenters', roadCenters, 'marking', marking, ...
    'laneSpecification', laneSpecification);
roadConfigs{numel(roadConfigs) + 1} = tempRoad;

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [17.1293569350258 -23.0936133851758 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car', ...
    'Yaw', 94.0946);
% speed = [10;10;10;10;10];
% trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [48.2082836409181 13.6307433994089 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [48.2082836409181 13.6307433994089 0;
    18.9 10.3 0;
    5 4 0;
    3.1 -6.5 0;
    6.2 -40.1 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;7;10;10;10];
waittime = [0;0;0;0;0];
yaw = NaN(1, numel(speed));
car1Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car1Status;
trajectory(car1, waypoints, speed, waittime);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [65.7835406304499 18.7337275681734 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');
waypoints = [65.7835406304499 18.7337275681734 0;
    20.5 13.9 0;
    3 5.1 0;
    1.43 2.48 0.01;
    0.12 -10.29 0.01;
    1.43 -30.67 0.01;
    3.6 -48.5 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;3;5;8;10;10;10];
waittime = [0;0;0;0;0;0;0];
yaw = NaN(1, numel(speed));
car2Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car2Status;
trajectory(car2, waypoints, speed, waittime);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-16.5032246492048 1.20569669954366 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');
waypoints = [-16.5032246492048 1.20569669954366 0;
    -1.1 4 0;
    10.5 11 0;
    12.7 24.9 0;
    10.9 44.1 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;7;10;10;10];
waittime = [0;0;0;0;0];
yaw = NaN(1, numel(speed));
car3Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car3Status;
trajectory(car3, waypoints, speed, waittime);

car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-4.34003885255375 46.0878003607211 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');
waypoints = [-4.34003885255375 46.0878003607211 0;
    0.6 15.2 0;
    0.3 -9.7 0;
    5.2 -57.2 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;7;10;10];
waittime = [0;0;0;0];
yaw = NaN(1, numel(speed));
car4Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car4Status;
trajectory(car4, waypoints, speed, waittime);

car5 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-4.29303749385384 62.7431900612638 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car5');
waypoints = [-4.29303749385384 62.7431900612638 0;
    -0.9 48.5 0;
    3.9 17.3 0;
    7 7.1 0;
    17.9 3.9 0;
    34.8 2.4 0;
    71.6 3.4 0];
actorWaypoints{numel(actorWaypoints) + 1} = waypoints;
speed = [10;7;5;10;10;10;10];
waittime = [0;0;0;0;0;0;0];
yaw = NaN(1, numel(speed));
car5Status = struct('speed', speed, 'waittime', waittime, 'yaw', yaw);
allStatus{numel(allStatus) + 1} = car5Status;
trajectory(car5, waypoints, speed, waittime);

